# Generated by Django 5.2.7 on 2025-11-03 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия автора",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя автора",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Имя",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Отчество автора (если есть)",
                        max_length=100,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Дата рождения автора", null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "death_date",
                    models.DateField(
                        blank=True,
                        help_text="Дата смерти автора (если применимо)",
                        null=True,
                        verbose_name="Дата смерти",
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True, help_text="Краткая биография автора", null=True, verbose_name="Биография"
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True, help_text="Ссылка на фотографию автора", null=True, verbose_name="Фото автора"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Пользователь, создавший автора",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["last_name"], name="authors_aut_last_na_13323b_idx"),
                    models.Index(fields=["first_name"], name="authors_aut_first_n_fe0d8b_idx"),
                ],
            },
        ),
    ]
