# Generated by Django 5.2.7 on 2025-11-03 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="photo_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png", "gif"])],
                verbose_name="Фото автора",
            ),
        ),
    ]
