# Generated by Django 5.2.7 on 2025-11-03 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="До 255 символов", max_length=255, verbose_name="Название книги"),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="Международный стандартный номер книги",
                        max_length=17,
                        null=True,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "publication_year",
                    models.PositiveIntegerField(
                        help_text="Год выпуска (1450–2030)",
                        validators=[
                            django.core.validators.MinValueValidator(1450),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                        verbose_name="Год издания",
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="Количество страниц"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="русский",
                        help_text="Язык издания (до 50 символов)",
                        max_length=50,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Подробное описание книги", null=True, verbose_name="Аннотация"
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True,
                        help_text='Номер издания (например, "2‑е изд.")',
                        max_length=50,
                        null=True,
                        verbose_name="Издание",
                    ),
                ),
                (
                    "available_copies",
                    models.PositiveIntegerField(
                        default=0, help_text="Сколько копий сейчас в наличии", verbose_name="Доступных экземпляров"
                    ),
                ),
                (
                    "total_copies",
                    models.PositiveIntegerField(
                        default=1, help_text="Общее количество копий в фонде", verbose_name="Всего экземпляров"
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(
                        blank=True, help_text="URL изображения обложки", null=True, verbose_name="Ссылка на обложку"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "author",
                    models.ForeignKey(
                        help_text="ФИО автора",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="authors.author",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Пользователь системы, добавивший книгу",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                    models.Index(fields=["author"], name="books_book_author__709385_idx"),
                    models.Index(fields=["isbn"], name="books_book_isbn_54becd_idx"),
                ],
            },
        ),
    ]
