# Generated by Django 5.2.7 on 2025-11-03 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                help_text="Жанр книги",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genres.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png", "gif"])],
                verbose_name="Обложка",
            ),
        ),
    ]
