# Generated by Django 5.2.7 on 2025-11-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_alter_author_photo_url"),
        ("books", "0002_book_genre_alter_book_cover_image"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="books_book_author__709385_idx",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(
                help_text="ФИО автора или список авторов книги",
                related_name="books",
                to="authors.author",
                verbose_name="Авторы",
            ),
        ),
    ]
