# Generated by Django 5.2.7 on 2025-11-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_book_books_book_author__709385_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "copy_id",
                    models.CharField(
                        help_text='Уникальный идентификатор экземпляра (например, "GP-001")',
                        max_length=50,
                        unique=True,
                        verbose_name="ID экземпляра",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Доступно"),
                            ("loaned", "Выдано"),
                            ("reserved", "Зарезервировано"),
                            ("damaged", "Повреждено"),
                            ("lost", "Утеряно"),
                        ],
                        default="available",
                        help_text="Текущий статус экземпляра",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        blank=True,
                        help_text="Когда экземпляр поступил в фонд",
                        null=True,
                        verbose_name="Дата поступления",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="Ссылка на основную запись книги",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Экземпляр книги",
                "verbose_name_plural": "Экземпляры книг",
                "indexes": [
                    models.Index(fields=["copy_id"], name="books_booki_copy_id_ff04f6_idx"),
                    models.Index(fields=["status"], name="books_booki_status_a99bab_idx"),
                ],
            },
        ),
    ]
