# Generated by Django 5.2.7 on 2025-11-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text='Краткое название жанра, например: "Фантастика", "Детектив"',
                        max_length=100,
                        unique=True,
                        verbose_name="Название жанра",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Подробное описание особенностей жанра",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Число для сортировки жанров в списках (меньше число — выше в списке)",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Если снято, жанр не будет отображаться в интерфейсе",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Пользователь, создавший автора",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал запись",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Основной жанр, к которому относится данный поджанр",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subgenres",
                        to="genres.genre",
                        verbose_name="Родительский жанр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="genres_genr_name_8bd7bd_idx"),
                    models.Index(fields=["parent"], name="genres_genr_parent__a1e82e_idx"),
                    models.Index(fields=["is_active"], name="genres_genr_is_acti_dadddd_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("name",), name="unique_genre_name")],
            },
        ),
    ]
