# Generated by Django 5.2.7 on 2025-11-03 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_book_genre_alter_book_cover_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookLoan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("loan_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата выдачи")),
                ("return_date", models.DateTimeField(blank=True, null=True, verbose_name="Дата возврата")),
                ("is_returned", models.BooleanField(default=False, verbose_name="Возвращена")),
                ("due_date", models.DateTimeField(blank=True, null=True, verbose_name="Срок возврата")),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book", verbose_name="Книга"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выдача книги",
                "verbose_name_plural": "Выдачи книг",
                "ordering": ["-loan_date"],
            },
        ),
    ]
