# Generated by Django 5.2.7 on 2025-11-06 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_bookinstance"),
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookloan",
            options={
                "ordering": ["-loan_date"],
                "verbose_name": "Выдача экземпляра",
                "verbose_name_plural": "Выдачи экземпляров",
            },
        ),
        migrations.RemoveField(
            model_name="bookloan",
            name="book",
        ),
        migrations.AddField(
            model_name="bookloan",
            name="book_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Какой именно экземпляр выдан",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.bookinstance",
                verbose_name="Экземпляр книги",
            ),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Кто оформил выдачу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loans_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал запись",
            ),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="Планируемая дата возврата", null=True, verbose_name="Срок возврата"
            ),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="is_returned",
            field=models.BooleanField(default=False, help_text="Отметка о возврате", verbose_name="Возвращена"),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Дополнительные комментарии (например, повреждения)", verbose_name="Примечания"
            ),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="user",
            field=models.ForeignKey(
                help_text="Кто взял книгу",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Читатель",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookloan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_returned", False)), fields=("book_instance",), name="unique_active_loan"
            ),
        ),
    ]
